### PR TITLE
David cleaning

### PR DESCRIPTION
**Pull request by xavdid**
Reorganized a ton of stuff. Namely:
- deleted a ton of repeated HTML code. There's now a base `layout.erb` which has all of your CSS and JS includes. Each page is inserted into the `yield` in the middle of the page. Everything should work the same. 
- added `Dotenv`, a nice ruby utility that reads out of a local `.env` file on startup. I'm not sure how you're setting your api keys and stuff now (globally, probably?) but now you just make a file in the folder that stores it. **MAKE SURE NOT TO CHECK IT INTO GIT**. 
- Ran `main.js` through the [Sublime Text JS Linter](https://github.com/SublimeLinter/SublimeLinter-jshint) which popped up a bunch of errors (mostly missing semi-colons, but also some other things). I'd go through and make sure everything makes sense. It's worth noting that I couldn't get stats to show up with this version. Worth nothing that your time filter was also giving me issues, so I commented it out of the views. It seems like it's a JS issue since, when clicking `go`, I didn't see any HTTP requests get fired. It also could be because I branched off of a slightly older commit (37efc49), which also could explain the merge conflicts. 

Your original issue was that you had hella copies of each js library in weird places. They're now all standardized into `public/lib`. To install them, use bower (first `npm install -g bower`, then `bower install`), a front-end js manager. These typically shouldn't be checked into source (because they can be reinstalled for each new person/environment). In your case, you may want to do that since heroku won't by default run `bower install` in a ruby project. Your other options is to change the heroku buildpack per [these](https://github.com/qnyp/heroku-buildpack-ruby-bower) instructions so that you can install node-based things too (which bower is). 

Hopefully this helps more than it hurts and will let you develop with fewer tricky issues. Let me know if you need explanations on anything.

### CODE REVIEW

**Comment by BTA02** [comment]
I can't get my javascript functions to work. That's the last problem. Take a look? @Xavdidtheshadow

**Comment by xavdid** [comment]
I was having trouble as well. Angular is a pain like that sometimes. Do you want to take the time to split stuff into separate controllers? Right now you have one huge thing. It'd be good to be able to narrow down what the issue is. Right now, it could be anything. 

~DB

**Comment by BTA02** [comment]
We're this far. Let's break stuff down. What is a controller?

**Comment by xavdid** [comment]
Sure. So angular is implementing a design pattern called [MVC](http://www.tutorialspoint.com/angularjs/angularjs_mvc_architecture.htm): Model, View, Controller. 

the Model is where the data stored (eg: `ng-model`). The View is what the users sees (buttons, etc). The Controller is the code that ties those together (literally called `StatsController` or something). (Aside, angular is a little weird because the model is very closely integrated with the controller since it lives on the controller's scope, but traditionally the model is a database or something.)

The controller's core purpose is to tie functionality together and act as a messenger for the view and the model. See [this SO answer](http://stackoverflow.com/a/1015853/1825390). 

Ideally, you're only loading 1 main controller per page, and it's individual to that page. So, there'll be `ReadStatsController`, `WriteStatsController`, `VideoController`, etc. You can put these all in your main js  file (they can also be split out, but that's not necessary). They're initialized on the page you want them with the `ng-controller` directive. But, instead of putting that in the layout, the layout will have no controller and then the first `div` for each partial will init the proper controller. 

The only other thing is that all the controllers are separate, so anything that you use in multiple (say, reading from a database (which you don't do in the js, so it's fine)) needs to go somewhere. Angular provides "Services" for this exact purpose, which are functions you can inject into controllers. 

Does that make sense. It seems like you can make some fairly distinct controllers and clean up your code dramatically.

**Comment by BTA02** [comment]
Okay, so I don't know how to set that up. Like, do I keep `var statsApp = angular.module('statsApp', [])` at the top of the main.js? I'll be looking around, but if you threw in some forms, I wouldn't complain.

**Comment by xavdid** [comment]
Check out my refbook repository. It's sinatra with some very light angular. I can also make a simple example 

~DB

**Comment by xavdid** [comment]
Here's a dirt simple angular/sinatra example: https://dl.dropboxusercontent.com/u/20865525/angsin.zip

Run it with `bundle exec ruby angsin.rb`

Let me know if that does or doesn't make sense.

**Pull request merged**
